'use client'

import Link from 'next/link'

const attempts = [
  { id: '01', slug: 'parking-lot', title: 'PARKING LOT', focus: 'Object Modelling · Relationships', difficulty: 'EASY', time: '~45 MIN', status: 'REVIEWED', action: 'VIEW ATTEMPT →' },
  { id: '02', slug: 'elevator-system', title: 'ELEVATOR SYSTEM', focus: 'State Management · Coordination', difficulty: 'MEDIUM', time: '~60 MIN', status: 'REVIEWED', action: 'VIEW ATTEMPT →' },
  { id: '03', slug: 'vending-machine', title: 'VENDING MACHINE', focus: 'State Transitions · Extensibility', difficulty: 'MEDIUM', time: '~45 MIN', status: 'IN PROGRESS', action: 'CONTINUE →' },
  { id: '04', slug: 'library-management', title: 'LIBRARY MANAGEMENT', focus: 'Domain Modelling · Abstraction', difficulty: 'EASY', time: '~45 MIN', status: 'DRAFT', action: 'CONTINUE →' },
]

function BrandMark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /><b /><b /></span> }
export function AttemptsNavbar() { return <header className="site-nav"><Link className="brand" href="/"><BrandMark /><span>DESIGNFORGE</span></Link><nav aria-label="Primary navigation"><Link className="nav-link" href="/">PROBLEMS</Link><Link className="nav-link active" href="/attempts">MY ATTEMPTS</Link></nav><button className="avatar" aria-label="Open profile for K">K</button></header> }

export function AttemptsPage() {
  return <main className="page-shell attempts-page"><AttemptsNavbar /><section className="attempts-intro"><div><p className="eyebrow">MY WORK</p><h1>MY ATTEMPTS</h1><p className="intro-description">Review your previous design decisions, continue saved drafts, and track how your system design thinking evolves.</p></div><div className="attempt-count"><strong>08</strong><span>ATTEMPTS</span></div></section><div className="attempts-rule" /><div className="attempt-filters"><button className="selected">ALL</button><button>REVIEWED</button><button>IN PROGRESS</button><button>DRAFTS</button></div><section className="attempt-list" aria-label="Previous attempts">{attempts.map((attempt) => <Link className="attempt-row" href={attempt.status === 'REVIEWED' ? `/attempts/${attempt.slug}` : `/practice/${attempt.slug}`} key={attempt.id}><span className="attempt-number">{attempt.id}</span><span className="attempt-copy"><strong>{attempt.title}</strong><small>{attempt.focus}</small></span><span className="attempt-meta"><small>{attempt.difficulty}</small><small>{attempt.time}</small></span><span className={`attempt-status ${attempt.status === 'REVIEWED' ? 'reviewed' : ''}`}>{attempt.status}</span><span className="attempt-action">{attempt.action}</span></Link>)}</section><footer className="footer-note">A practice space for better design decisions.</footer></main>
}

const reviewSections = [
  ['CLEAR RESPONSIBILITIES', 'Vehicle, ParkingFloor and ParkingSpot have distinct responsibilities, reducing coupling between domain concerns.'],
  ['GOOD DOMAIN MODELLING', 'The relationship between floors and parking spots is explicit and easy to extend.'],
  ['EXTENSIBLE VEHICLE SUPPORT', 'Vehicle-specific sizing can be handled without changing the allocation flow.'],
]
const improveSections = [
  ['ALLOCATION STRATEGY', 'Define how the system selects the best available parking spot when multiple compatible spots exist.'],
  ['TICKET OWNERSHIP', 'Clarify whether Ticket coordinates payment lifecycle state or delegates payment responsibility elsewhere.'],
  ['FUTURE EXTENSIBILITY', 'Consider separating pricing rules from ParkingLot so pricing policies can evolve independently.'],
]
function FeedbackSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="feedback-section"><div className="feedback-heading"><span>{number}</span><h2>{title}</h2></div>{children}</section> }
function ReviewItems({ items }: { items: string[][] }) { return <div className="review-items">{items.map(([title, text], i) => <div className="review-item" key={title}><span>{String(i + 1).padStart(2, '0')}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div> }
function AttemptSidebar() { return <aside className="attempt-sidebar"><p className="section-label">PROBLEM</p><p className="sidebar-summary">Design a multi-floor parking system that handles different vehicle types, spot allocation, entry and exit.</p><p className="section-label sidebar-label">YOUR REQUIREMENTS</p><ol>{['Support multiple parking floors', 'Handle Motorcycle, Car and Truck', 'Allocate appropriate available parking spots', 'Generate tickets on entry and payment on exit', 'Track availability by floor and spot type'].map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}</li>)}</ol><div className="sidebar-status"><p className="section-label">ATTEMPT STATUS</p><strong>REVIEWED</strong><span>SUBMITTED</span><small>SEPT 08, 2026</small></div></aside> }
export function AttemptDetailsPage() { return <main className="page-shell attempt-details"><AttemptsNavbar /><Link href="/attempts" className="back-link">← ALL ATTEMPTS</Link><header className="attempt-header"><div><p className="eyebrow">ATTEMPT REVIEW</p><h1>PARKING LOT</h1><p className="attempt-subtitle">EASY · ~45 MIN · SUBMITTED</p></div><div className="assessment"><span>OVERALL ASSESSMENT</span><strong>82<small>/100</small></strong><em>STRONG FOUNDATION</em></div></header><div className="details-layout"><AttemptSidebar /><article className="feedback-content"><div className="content-intro"><p className="section-label">AI DESIGN REVIEW</p><p>A structured evaluation of your design decisions and reasoning.</p></div><FeedbackSection number="01" title="DESIGN SUMMARY"><p className="feedback-copy">Your design separates vehicle classification, parking allocation and ticket lifecycle responsibilities. The core object model provides a clear foundation for multiple floors and parking spot types.</p></FeedbackSection><FeedbackSection number="02" title="WHAT WORKED WELL"><ReviewItems items={reviewSections} /></FeedbackSection><FeedbackSection number="03" title="AREAS TO IMPROVE"><ReviewItems items={improveSections} /></FeedbackSection><FeedbackSection number="04" title="SECTION REVIEW"><div className="section-reviews">{[['CLASSES & RESPONSIBILITIES','A ParkingLot owns multiple ParkingFloors and coordinates entry and exit. Vehicle represents the type and dimensions of a vehicle. ParkingSpot determines whether it can accommodate a vehicle.','Strong separation of core domain concepts. Consider clarifying which object owns spot allocation logic.','8.5 / 10'],['OBJECT RELATIONSHIPS','A ParkingFloor contains multiple ParkingSpots. A Ticket references the assigned vehicle and parking spot.','The containment relationships are clear. Consider defining the lifecycle relationship between Ticket and Payment more explicitly.','8.0 / 10'],['DESIGN DECISIONS','I chose the nearest compatible parking spot because it keeps allocation simple.','The decision is reasonable for a first version. For larger systems, explain how “nearest” is calculated.','7.5 / 10']].map(([title, response, feedback, score]) => <div className="section-review" key={title}><h3>{title}</h3><div><span>USER RESPONSE</span><p>{response}</p></div><div><span>AI REVIEW</span><p>{feedback}</p></div><strong>SCORE: {score}</strong></div>)}</div></FeedbackSection><section className="next-challenge"><p className="section-label">NEXT DESIGN CHALLENGE</p><p>Try the Elevator System challenge next to practice state management, coordination and dispatch strategies.</p><Link className="submit-button" href="/practice/elevator-system">START ELEVATOR SYSTEM →</Link></section><div className="details-actions"><Link href="/attempts">← BACK TO ATTEMPTS</Link><Link className="submit-button" href="/practice/parking-lot">TRY AGAIN →</Link></div></article></div></main> }
export function EmptyAttempts() { return <div className="empty-attempts"><p className="section-label">NO ATTEMPTS YET</p><p>Start with a real-world system design challenge and your work will appear here.</p><Link className="submit-button" href="/">EXPLORE PROBLEMS →</Link></div> }
