'use client'

import Link from 'next/link'
import { useState } from 'react'

type Slug = 'parking-lot' | 'elevator-system' | 'vending-machine' | 'library-management'
type Section = { title: string; prompt: string; placeholder: string }

const data: Record<Slug, { number: string; title: string; difficulty: string; time: string; focus: string; context: string; requirements: string[]; sections: Section[] }> = {
  'parking-lot': { number: '01', title: 'PARKING LOT', difficulty: 'EASY', time: '~45 MIN', focus: 'RESPONSIBILITIES · OBJECT RELATIONSHIPS', context: 'Design a parking lot system that manages multiple floors, different vehicle types and parking spot allocation. The system should support vehicle entry and exit and track parking availability.', requirements: ['Support multiple parking floors, each with multiple parking spots.', 'Handle Motorcycle, Car and Truck vehicle types.', 'Allocate an appropriate nearest available spot to an incoming vehicle.', 'Generate a ticket on entry and process payment on exit.', 'Track availability based on floor and parking spot type.'], sections: [{ title: 'CLASSES & RESPONSIBILITIES', prompt: 'Identify the major objects and describe what each one owns.', placeholder: 'ParkingLot — owns floors and coordinates entry…\nVehicle — represents type and dimensions…' }, { title: 'OBJECT RELATIONSHIPS', prompt: 'Explain containment, associations and the relationships that matter.', placeholder: 'A ParkingFloor contains many ParkingSpots. A Ticket references…' }, { title: 'DESIGN DECISIONS', prompt: 'What trade-off did you make here? Explain the decisions that shape your design.', placeholder: 'I chose a strategy for spot allocation because…' }] },
  'elevator-system': { number: '02', title: 'ELEVATOR SYSTEM', difficulty: 'MEDIUM', time: '~60 MIN', focus: 'STATE MANAGEMENT · COORDINATION', context: 'Design an elevator control system for a multi-floor building with multiple elevator cars. Efficiently coordinate requests while considering direction, movement and capacity.', requirements: ['Support multiple elevator cars serving multiple floors.', 'Represent internal and external floor requests.', 'Coordinate movement, direction and capacity.', 'Keep elevator state changes explicit and understandable.', 'Leave room for alternative dispatch strategies.'], sections: [{ title: 'CORE ENTITIES', prompt: 'What are the important objects? What does each object represent?', placeholder: 'ElevatorCar represents movement and capacity…\nRequest represents a destination and direction…' }, { title: 'ELEVATOR STATES', prompt: 'Describe possible states, transitions and the events that cause them.', placeholder: 'Idle → Moving Up when a compatible request is assigned…\nMoving → Stopped when the target floor is reached…' }, { title: 'REQUEST FLOW', prompt: 'How are requests represented, received and assigned?', placeholder: 'A controller receives a request and asks the dispatcher…' }, { title: 'DISPATCH / SCHEDULING', prompt: 'How does the system choose an elevator? What trade-offs exist?', placeholder: 'The dispatcher prioritizes cars already moving in the requested direction…' }] },
  'vending-machine': { number: '03', title: 'VENDING MACHINE', difficulty: 'MEDIUM', time: '~45 MIN', focus: 'STATE TRANSITIONS · EXTENSIBILITY', context: 'Design a vending machine that manages product inventory, selection, payment, dispensing and returning change. The design should remain extensible for additional payment methods or product types.', requirements: ['Manage products, stock levels and product selection.', 'Accept payment and validate sufficient funds.', 'Dispense a product and return change.', 'Handle cancellation, sold-out products and failed payment.', 'Support new payment methods without changing the machine core.'], sections: [{ title: 'CORE OBJECTS', prompt: 'What are the main objects in the domain and what do they own?', placeholder: 'Machine coordinates the session…\nInventory owns stock…\nPaymentProcessor owns authorization…' }, { title: 'STATES & TRANSITIONS', prompt: 'What states can the machine be in? What events trigger transitions?', placeholder: 'READY —select→ AWAITING_PAYMENT —pay→ DISPENSING…' }, { title: 'PAYMENT STRATEGY', prompt: 'How should the machine depend on payment behaviour?', placeholder: 'PaymentMethod exposes a charge contract so cash, card and…' }, { title: 'DESIGN FOR EXTENSIBILITY', prompt: 'What is likely to change, and how would you add it safely?', placeholder: 'New payment methods should be added as implementations, not…' }] },
  'library-management': { number: '04', title: 'LIBRARY MANAGEMENT', difficulty: 'EASY', time: '~45 MIN', focus: 'DOMAIN MODELLING · ABSTRACTION', context: 'Design a library management system that manages books, members, borrowing and availability.', requirements: ['Represent books and their availability.', 'Allow members to borrow and return items.', 'Track loans and due dates.', 'Keep domain responsibilities clear and cohesive.', 'Leave room for future borrowing policies or item types.'], sections: [{ title: 'DOMAIN ENTITIES', prompt: 'What are the important entities? What information or behaviour belongs to each?', placeholder: 'Book — title, author and availability…\nMember — identity and active loans…' }, { title: 'RESPONSIBILITIES', prompt: 'What should each object be responsible for? Avoid mixing unrelated concerns.', placeholder: 'Loan owns the borrowing agreement and due date…' }, { title: 'RELATIONSHIPS', prompt: 'How do books, members and borrowing relate?', placeholder: 'A Member can have many Loans. A Loan references one LibraryItem…' }, { title: 'ABSTRACTIONS & EXTENSIBILITY', prompt: 'What might change later? How could the design support it?', placeholder: 'LibraryItem could abstract books and future media types…' }] },
}

function BrandMark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /><b /><b /></span> }
function Navbar() { return <header className="site-nav practice-nav"><Link className="brand" href="/"><BrandMark /><span>DESIGNFORGE</span></Link><nav aria-label="Primary navigation"><Link className="nav-link active" href="/">PROBLEMS</Link><a className="nav-link" href="#attempts">MY ATTEMPTS</a></nav><button className="avatar" aria-label="Open profile for K">K</button></header> }
function ActionBar({ saved, onSave, onSubmit }: { saved: boolean; onSave: () => void; onSubmit: () => void }) { return <div className="action-bar"><button className="save-button" onClick={onSave}>{saved ? 'DRAFT SAVED' : 'SAVE DRAFT'}</button><button className="submit-button" onClick={onSubmit}>SUBMIT DESIGN <span aria-hidden="true">→</span></button></div> }
function EditorSection({ section, value, onChange, index }: { section: Section; value: string; onChange: (v: string) => void; index: number }) { return <section className="editor-section"><div className="editor-heading"><span className="section-index">{String(index + 1).padStart(2, '0')}</span><div><h2>{section.title}</h2><p>{section.prompt}</p></div></div><textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={section.placeholder} aria-label={section.title} /></section> }

function Brief({ problem }: { problem: typeof data[Slug] }) { return <aside className="practice-brief"><p className="eyebrow">PROBLEM BRIEF</p><h1>{problem.title}</h1><p className="brief-context">{problem.context}</p><div className="brief-meta"><span>{problem.difficulty}</span><span>{problem.time}</span><span>{problem.focus}</span></div><div className="requirements"><p className="section-label">REQUIREMENTS</p><ol>{problem.requirements.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}</li>)}</ol></div></aside> }
function ParkingWorkspace({ problem, values, setValues }: any) { return <div className="parking-workspace"><div className="vehicle-strip"><span className="section-label">VEHICLE TYPES</span><span>MOTORCYCLE</span><span>CAR</span><span>TRUCK</span></div><div className="editor-grid">{problem.sections.map((s: Section, i: number) => <EditorSection key={s.title} section={s} index={i} value={values[i]} onChange={(v) => setValues((x: string[]) => x.map((a, n) => n === i ? v : a))} />)}</div></div> }
function ElevatorWorkspace({ problem, values, setValues }: any) { return <div className="elevator-workspace"><div className="floor-rail" aria-hidden="true"><span>12</span><i /><span>08</span><i /><span>04</span><i /><span>01</span></div><div className="elevator-editors">{problem.sections.map((s: Section, i: number) => <EditorSection key={s.title} section={s} index={i} value={values[i]} onChange={(v) => setValues((x: string[]) => x.map((a, n) => n === i ? v : a))} />)}</div></div> }
function VendingWorkspace({ problem, values, setValues }: any) { return <div className="vending-workspace"><div className="flow-rail"><span>INPUT</span><i>→</i><span>VALIDATE</span><i>→</i><span>PAYMENT</span><i>→</i><span>DISPENSE</span><i>→</i><span>COMPLETE</span></div><div className="flow-editors">{problem.sections.map((s: Section, i: number) => <EditorSection key={s.title} section={s} index={i} value={values[i]} onChange={(v) => setValues((x: string[]) => x.map((a, n) => n === i ? v : a))} />)}</div></div> }
function LibraryWorkspace({ problem, values, setValues }: any) { return <div className="library-workspace"><div className="entity-map" aria-label="Domain concepts"><span>BOOK</span><span>MEMBER</span><span>LOAN</span><span>AVAILABILITY</span></div><div className="library-editors">{problem.sections.map((s: Section, i: number) => <EditorSection key={s.title} section={s} index={i} value={values[i]} onChange={(v) => setValues((x: string[]) => x.map((a, n) => n === i ? v : a))} />)}</div></div> }

export function PracticePage({ slug }: { slug: Slug }) { const problem = data[slug]; const [values, setValues] = useState(problem.sections.map(() => '')); const [saved, setSaved] = useState(false); const [submitted, setSubmitted] = useState(false); const Workspace = slug === 'parking-lot' ? ParkingWorkspace : slug === 'elevator-system' ? ElevatorWorkspace : slug === 'vending-machine' ? VendingWorkspace : LibraryWorkspace; return <main className={`practice-shell practice-${slug}`}><Navbar /><Link href="/" className="back-link">← ALL PROBLEMS</Link><div className="practice-layout"><Brief problem={problem} /><section className="design-workspace"><div className="workspace-header"><div><p className="eyebrow">YOUR DESIGN</p><p className="workspace-note">Translate the requirements into a clear object model.</p></div><span className="workspace-status">{submitted ? 'SUBMITTED · EVALUATING' : 'IN PROGRESS'}</span></div><Workspace problem={problem} values={values} setValues={setValues} /><ActionBar saved={saved} onSave={() => setSaved(true)} onSubmit={() => setSubmitted(true)} /></section></div></main> }

export const practiceSlugs = Object.keys(data) as Slug[]
export function isPracticeSlug(value: string): value is Slug { return practiceSlugs.includes(value as Slug) }
